# Nome do projeto
spring.application.name=familia-naval-api

# Context Path Global
server.servlet.context-path=/api/v1

# Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://10.210.129.23:5432/web
spring.datasource.username=web
spring.datasource.password=@piD1g1t@l
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
# Observação: Remover 'database-platform' evita o WARN de suporte do PostgreSQL 9.2 no Hibernate 6/7
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Criptografia PGP
app.crypto.key=bf