# ==========================================
# Configurações Globais / Comuns
# ==========================================
spring.application.name=familia-naval-api
server.servlet.context-path=/api/v1

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Criptografia PGP
app.crypto.key=bf


---
# ==========================================
# Perfil: Trabalho (A bordo / Rede Corporativa)
# ==========================================
spring.config.activate.on-profile=trabalho
spring.datasource.url=jdbc:postgresql://10.210.129.23:5432/web
spring.datasource.username=web
spring.datasource.password=@piD1g1t@l
spring.datasource.driver-class-name=org.postgresql.Driver


---
# ==========================================
# Perfil: Local (Modem / Servidor Externo)
# ==========================================
spring.config.activate.on-profile=local
spring.datasource.url=jdbc:postgresql://localhost:5432/web
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver